# Generated by Django 3.1.5 on 2021-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IUTDeadlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='SophomoreSubjects',
        ),
    ]
