# Generated by Django 3.1.5 on 2021-01-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IUTDeadlines', '0004_auto_20210122_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sophomoredeadlines',
            options={},
        ),
    ]
